import Foundation
import FoundationModels
import SwiftContextManagement

struct MockConversationPreset {
    let name: String
    let description: String
    let messages: [(role: MessageRole, content: String)]
    let transcript: Transcript
}

enum MockConversationPresets {
    static let all: [MockConversationPreset] = [
        travelPlanning,
        cookingTips,
        bookDiscussion
    ]
    
    static let travelPlanning: MockConversationPreset = {
        let messages: [(role: MessageRole, content: String)] = [
            (.user, "I'm planning a trip to Japan next month. What are the must-see places I should visit?"),
            (.assistant, "Japan is amazing! Here are some must-see places: Tokyo for the modern city experience and amazing food, Kyoto for temples and traditional culture, Osaka for the food scene, Hiroshima for its historical significance, and Nara for the deer park. I'd also recommend checking out Mount Fuji if weather permits, and spending a night in a traditional ryokan for the full cultural experience."),
            (.user, "How many days would you recommend for a first-time visitor?"),
            (.assistant, "For a first-time visitor, I'd suggest at least 10-14 days to really experience the country without feeling too rushed. This gives you about 3-4 days in Tokyo, 2-3 days in Kyoto, 1-2 days in Osaka, and time for travel between cities. If you can spare 2-3 weeks, you can add more destinations like Nara, Hiroshima, or even a trip to Hokkaido or Okinawa."),
            (.user, "What's the best way to get around Japan? Should I get a JR Pass?"),
            (.assistant, "The Japan Rail Pass (JR Pass) is usually worth it if you're planning to travel between cities by bullet train (Shinkansen). It allows unlimited travel on JR trains for 7, 14, or 21 days. However, you need to buy it before arriving in Japan. For city travel, local trains and subways are efficient and affordable. Consider getting an IC card like Suica or Pasmo for easy local transportation."),
            (.user, "What about food? I've heard Japanese food is incredible but I'm not sure what to try."),
            (.assistant, "Japanese cuisine is fantastic! Definitely try sushi at a good sushi bar, ramen from local shops, tempura, tonkatsu (breaded pork cutlet), and takoyaki (octopus balls) especially in Osaka. Don't miss trying wagyu beef if budget allows, and explore the izakayas (Japanese pubs) for a great social dining experience. Convenience store food is also surprisingly good and affordable for quick meals."),
            (.user, "I'm worried about the language barrier. Will I be able to get around?"),
            (.assistant, "You'll be fine! While English isn't widely spoken outside tourist areas, most signs in train stations are bilingual, and many restaurants have picture menus or English menus. People are very helpful even with limited English. I recommend learning a few basic phrases like \"arigato\" (thank you) and \"sumimasen\" (excuse me). Translation apps like Google Translate with camera function are also very helpful."),
            (.user, "What about accommodation? Should I stay in hotels or try something more traditional?"),
            (.assistant, "I'd suggest a mix! Try staying in a traditional ryokan for at least one night to experience Japanese hospitality, tatami rooms, and kaiseki meals. Western-style hotels are comfortable and convenient, especially in big cities. Capsule hotels can be a fun experience for budget travelers, and there are also excellent hostels available. Book in advance, especially during cherry blossom or autumn leaf seasons."),
            (.user, "When is the best time to visit Japan?"),
            (.assistant, "The best times are spring (March-May) for cherry blossoms and mild weather, and autumn (September-November) for beautiful fall foliage and comfortable temperatures. Summer can be hot and humid with typhoon season, and winter is cold but great for skiing in Hokkaido. Avoid Golden Week (late April-early May) and Obon (mid-August) as they're major holidays with crowded transportation."),
            (.user, "Any tips for visiting temples and shrines?"),
            (.assistant, "When visiting temples and shrines, remember to be respectful. You'll often need to remove your shoes, so wear shoes that are easy to slip on and off. Many places provide lockers. Bow slightly before entering temple gates, purify yourself at the chozuya (water pavilion) before praying, and be quiet and respectful inside. Photography rules vary by location, so check signs. Early morning visits are less crowded and offer a more peaceful experience."),
            (.user, "What should I pack? Any essentials I shouldn't forget?"),
            (.assistant, "Pack comfortable walking shoes - you'll do a lot of walking! Bring layers since weather can vary. A portable WiFi device or SIM card is very useful for navigation and translation. Cash is still king in Japan, so don't rely solely on cards. Bring an adapter for your electronics (Type A plugs). A small backpack or bag is handy for carrying purchases and taking off shoes at temples. Don't forget any medications you need, as pharmacies can be tricky with prescriptions."),
            (.user, "I'm interested in Japanese culture. What cultural experiences would you recommend?"),
            (.assistant, "Great question! Consider trying a traditional tea ceremony in Kyoto, which offers deep insight into Japanese aesthetics and philosophy. Visit a sumo stable if you can (book in advance), or watch a sumo tournament. Experience an onsen (hot spring bath) following proper etiquette. Try a calligraphy or pottery class. See a kabuki or noh theater performance. Visit during a local festival if possible - they're vibrant cultural showcases. Museums like the Tokyo National Museum offer excellent historical context."),
            (.user, "What are the best neighborhoods to stay in Tokyo? I want to experience different vibes."),
            (.assistant, "Tokyo has incredible diversity in neighborhoods! Shibuya is perfect for shopping, nightlife, and the famous scramble crossing - great for first-time visitors who want energy and convenience. Shinjuku offers skyscrapers, the Golden Gai bar district, and excellent train connections. Harajuku and Omotesando are trendy with unique fashion, cafes, and the Meiji Shrine nearby. Asakusa provides traditional atmosphere with Senso-ji Temple and old Tokyo charm. Ginza is upscale with luxury shopping and fine dining. Akihabara is the electronics and anime district. Roppongi has international restaurants and nightlife. I'd recommend staying in Shibuya or Shinjuku for convenience, but visiting other neighborhoods during the day."),
            (.user, "How do I handle money in Japan? Should I bring cash or use cards?"),
            (.assistant, "Japan is still very much a cash-based society, especially outside major cities. While credit cards are accepted at hotels, department stores, and many restaurants in Tokyo, you'll need cash for small shops, local restaurants, temples, markets, and transportation. ATMs are widely available at convenience stores (7-Eleven, FamilyMart, Lawson) and post offices - these accept international cards. Avoid bank ATMs as they often don't work with foreign cards. Bring some yen from home or exchange at the airport. IC cards (Suica/Pasmo) can be loaded with cash and used for trains, buses, and many purchases. Budget about 10,000-15,000 yen per day for food and activities. Always carry cash as backup - you'll need it more than you think!"),
            (.user, "What about tipping? I've heard it's not customary in Japan."),
            (.assistant, "Correct - tipping is NOT customary in Japan and can actually be considered rude or confusing. Japanese service is excellent by default, and workers take pride in their service without expecting extra payment. If you try to tip, staff may chase you down to return your money thinking you forgot it. The price you see is the price you pay - no tax surprises at checkout. However, there are a few exceptions: some high-end ryokans may have a service charge, and tour guides might accept tips if offered discreetly in an envelope. But for restaurants, taxis, hotels, and most services, no tipping is expected or necessary. The service culture is built into the price, so just enjoy the excellent hospitality!"),
            (.user, "I'm a vegetarian. Will I be able to find good food in Japan?"),
            (.assistant, "Vegetarianism can be challenging in Japan, but it's definitely possible with some planning. Many seemingly vegetarian dishes contain dashi (fish stock) or other hidden animal products. Look for restaurants with \"shojin ryori\" (Buddhist vegetarian cuisine) or \"vegan\" clearly marked. Major cities have more options - Tokyo and Kyoto have dedicated vegetarian and vegan restaurants. Convenience stores now have some vegetarian options clearly labeled. Learn key phrases: \"bejitarian\" (vegetarian), \"niku nashi\" (no meat), \"sakana nashi\" (no fish). Some chain restaurants like Coco Ichibanya (curry) and Mos Burger have vegetarian options. Indian restaurants are usually safe bets. Consider bringing a translation card explaining your dietary restrictions. It's getting easier, but still requires more effort than in many Western countries."),
            (.user, "What's the best way to experience cherry blossoms if I'm visiting in spring?"),
            (.assistant, "Cherry blossom season (sakura) is magical but requires planning! The season typically runs late March to early May, moving northward. Check sakura forecasts (sakura.weathermap.jp) before booking. Popular spots include Ueno Park in Tokyo (festival atmosphere), Meguro River (canal lined with trees), Shinjuku Gyoen (paid entry, less crowded), and Chidorigafuchi (moat with boat rentals). In Kyoto, Maruyama Park, Philosopher's Path, and Arashiyama are stunning. The best viewing is during \"hanami\" (flower viewing) - locals picnic under the trees. Arrive early (before 9am) for photos without crowds. Evening illuminations (yozakura) are also beautiful. Book accommodations well in advance as prices skyrocket. Be flexible with dates - peak bloom varies by 1-2 weeks each year. If you miss full bloom, you can still enjoy the falling petals (hanafubuki) which is equally beautiful!"),
            (.user, "How do I navigate the train system? It seems overwhelming."),
            (.assistant, "Japan's train system is actually very user-friendly once you understand the basics! The key is using Google Maps or Japan Travel app - they'll tell you exactly which train, platform, and time. Major stations have English signs. Get an IC card (Suica or Pasmo) - just tap in and out, no need to figure out fares. For long-distance travel, the JR Pass covers Shinkansen and JR trains. Local trains are color-coded and numbered. Platform numbers are clearly marked. Trains are punctual - if the app says 10:15, the train arrives at 10:15. Rush hour (7-9am, 5-7pm) is crowded but manageable. Don't worry about making mistakes - station staff are helpful, and you can always exit and re-enter. The system looks complex but is actually very logical and efficient once you start using it!"),
            (.user, "What about shopping? What should I buy and where?"),
            (.assistant, "Japan offers incredible shopping! For electronics, Akihabara in Tokyo has everything, but prices aren't always better than home. For unique items: traditional crafts in Kyoto (pottery, textiles, fans), stationery and art supplies (amazing quality), skincare and cosmetics (drugstores like Matsumoto Kiyoshi), matcha and Japanese snacks, anime/manga goods in Akihabara or Nakano Broadway, and high-quality kitchen knives. Tax-free shopping is available for tourists spending over 5,000 yen - bring your passport. Department stores like Isetan and Takashimaya have excellent food basements (depachika). Don Quijote stores are fun for quirky items. 100-yen stores (Daiso) are great for souvenirs. Remember to check voltage compatibility for electronics. Many stores offer tax refunds at the airport or in-store with your passport."),
            (.user, "I'm concerned about earthquakes. What should I know?"),
            (.assistant, "Japan experiences frequent small earthquakes, but major ones are rare. The country has excellent building codes and earthquake preparedness. If you feel shaking: stay calm, get under a sturdy table or desk, protect your head, and wait for shaking to stop. Most buildings are designed to withstand earthquakes. Hotels usually have emergency information in rooms. Download safety apps like \"Safety Tips\" from Japan Tourism. Know your hotel's evacuation route. In case of a major quake, follow instructions from staff or authorities. Tsunami warnings are broadcast in multiple languages. The likelihood of experiencing a significant earthquake during a short visit is very low, but being prepared is wise. Japan's infrastructure is among the world's best for earthquake safety, so you're in good hands."),
            (.user, "What's the etiquette for using public transportation?"),
            (.assistant, "Japanese public transport etiquette is important! On trains: keep conversations quiet or silent, turn phone to silent mode, don't talk on phones (texting is fine), give up priority seats for elderly/pregnant/disabled, let people exit before boarding, don't eat smelly food (light snacks are sometimes okay), keep bags on your lap or overhead, and stand on the left side of escalators (right side in Osaka/Kyoto). During rush hour, expect crowding - it's normal. Trains are generally very clean and quiet. If you're lost, step aside to check your phone rather than blocking the flow. Buses require exact change or IC card - some have change machines. Taxis have automatic doors - don't open them yourself. Following these norms shows respect and makes your journey smoother!"),
            (.user, "Can you recommend a detailed 14-day itinerary?"),
            (.assistant, "Absolutely! Here's a comprehensive 14-day itinerary: Days 1-4 Tokyo: Day 1 - Arrive, Shibuya, Harajuku, Meiji Shrine. Day 2 - Asakusa, Senso-ji, Tokyo Skytree, Ueno Park. Day 3 - Tsukiji Outer Market, Ginza, Imperial Palace East Gardens, Akihabara. Day 4 - Day trip to Nikko or Kamakura. Days 5-7 Kyoto: Day 5 - Travel to Kyoto (2.5 hours), Fushimi Inari Shrine, Gion district. Day 6 - Arashiyama Bamboo Grove, Tenryu-ji Temple, Kinkaku-ji (Golden Pavilion), Philosopher's Path. Day 7 - Kiyomizu-dera, traditional streets, tea ceremony, evening in Pontocho. Days 8-9 Nara/Osaka: Day 8 - Day trip to Nara (deer park, Todai-ji Temple), return to Kyoto. Day 9 - Travel to Osaka (30 min), Osaka Castle, Dotonbori food district, evening street food tour. Days 10-11 Hiroshima/Miyajima: Day 10 - Travel to Hiroshima (1.5 hours), Peace Memorial Park and Museum, Okonomiyaki lunch. Day 11 - Ferry to Miyajima Island, Itsukushima Shrine, hike Mount Misen, return to Hiroshima. Days 12-14 Return to Tokyo or explore more: Day 12 - Travel back to Tokyo, relax, last-minute shopping. Day 13 - Any missed Tokyo attractions, teamLab Borderless or teamLab Planets, final meals. Day 14 - Departure. This gives you a great mix of modern and traditional Japan!"),
            (.user, "What are some hidden gems or off-the-beaten-path destinations I should consider?"),
            (.assistant, "Great question! While Tokyo and Kyoto are must-sees, Japan has incredible hidden gems. Consider Kanazawa on the west coast - it's called 'Little Kyoto' with beautiful gardens, samurai districts, and excellent seafood markets, but far fewer tourists. Takayama in the Japanese Alps offers preserved Edo-period streets and is a gateway to the Shirakawa-go thatched-roof villages. Naoshima Island is an art lover's paradise with incredible contemporary art museums and installations. Yakushima Island has ancient cedar forests and is a UNESCO World Heritage site. The Izu Peninsula near Tokyo offers hot springs, beautiful coastlines, and is less touristy. Himeji Castle is Japan's most beautiful original castle (not a reconstruction). The Kiso Valley has a preserved post town on the old Nakasendo trail. These places offer authentic experiences away from the crowds while still being accessible."),
            (.user, "How do I handle the time difference and jet lag when arriving?"),
            (.assistant, "Japan is typically 9 hours ahead of Eastern US time or 13-16 hours ahead depending on your origin. To minimize jet lag: start adjusting your sleep schedule 2-3 days before departure, try to sleep on the plane if it's nighttime in Japan, stay hydrated and avoid alcohol during the flight, upon arrival, try to stay awake until local bedtime even if you're exhausted, get sunlight exposure during the day to reset your circadian rhythm, avoid napping longer than 20-30 minutes, and consider melatonin if needed. Many travelers find it easier to adjust going east to west (to Japan) than the reverse. The first day or two might be rough, but try to push through and get on local time quickly. Some people find it helpful to arrive in the morning so you have a full day to stay awake. Don't plan anything too demanding for your first day - just light sightseeing and staying awake until evening."),
            (.user, "What about internet and phone connectivity? Should I get a SIM card or portable WiFi?"),
            (.assistant, "You have several good options! Portable WiFi (pocket WiFi) is popular - you can rent one at the airport or have it delivered to your hotel. It provides unlimited data for multiple devices and is great if traveling with others. SIM cards are cheaper for single users and available at airports, convenience stores, or online. Major providers include NTT Docomo, SoftBank, and au. eSIM is becoming more common - check if your phone supports it. Many hotels and cafes offer free WiFi, but it's not as reliable as having your own connection. For navigation, Google Maps works excellently in Japan. Consider downloading offline maps as backup. Translation apps like Google Translate work well with camera function for menus and signs. Having reliable internet is crucial for navigation, translation, and staying connected. I'd recommend either a SIM card or pocket WiFi - both are affordable and make travel much easier. Book in advance online for better rates than airport counters."),
            (.user, "What cultural faux pas should I avoid to be respectful?"),
            (.assistant, "Being aware of cultural norms shows respect! Key things to avoid: don't eat or drink while walking (it's considered impolite), don't talk loudly on trains or in public spaces, don't point with one finger (use an open hand), don't tip (as mentioned, it can be confusing), don't wear shoes inside homes, ryokans, or some restaurants (follow the lead of others), don't blow your nose in public (excuse yourself to a restroom), don't stick chopsticks upright in rice (it's associated with funerals), don't pass food directly from chopstick to chopstick, don't be too direct or pushy in conversations, and don't take photos of people without permission. Do: bow slightly when greeting or thanking, say 'sumimasen' (excuse me) when passing or getting attention, be quiet and respectful in temples and shrines, follow the queue system (Japanese people are very orderly), and be patient and polite. Most Japanese people are very forgiving of tourists, but following these norms shows respect and will make your interactions smoother."),
        ]
        return MockConversationPreset(
            name: "Travel Planning",
            description: "Planning a trip with recommendations and tips (25+ messages)",
            messages: messages,
            transcript: createTranscript(from: messages)
        )
    }()
    
    static let cookingTips: MockConversationPreset = {
        let messages: [(role: MessageRole, content: String)] = [
            (.user, "I want to learn how to cook better. Where should I start?"),
            (.assistant, "Great question! Start with mastering basic techniques that form the foundation of good cooking. Learn how to properly chop vegetables, how to brown meat, how to make a good sauce, and how to season food correctly. Start with simple recipes and practice them until you're comfortable, then gradually try more complex dishes. Don't be afraid to make mistakes - that's how you learn!"),
            (.user, "What are the essential kitchen tools I should have?"),
            (.assistant, "For essential tools, I'd recommend: a good chef's knife and paring knife, a cutting board, measuring cups and spoons, mixing bowls in different sizes, a good skillet or frying pan, a saucepan, a sheet pan for roasting, wooden spoons, a whisk, and tongs. As you cook more, you can add specialty items, but these basics will handle most recipes. Invest in quality knives - they make a huge difference!"),
            (.user, "I always burn my food. What am I doing wrong?"),
            (.assistant, "Burning food usually happens because the heat is too high. Try cooking at lower temperatures and be patient - food takes time to cook properly. Preheat your pan before adding food, but then reduce heat slightly. Learn to control your heat based on what you're cooking. Also, don't overcrowd the pan - food needs space to cook evenly. Keep an eye on your food and adjust heat as needed."),
            (.user, "How do I know when meat is cooked properly?"),
            (.assistant, "The best way is to use a meat thermometer. For chicken, it should reach 165°F internally. For beef, medium-rare is around 130-135°F, medium is 140-145°F. You can also learn the touch method - comparing the firmness to parts of your hand. Remember that meat continues cooking after you remove it from heat (carryover cooking), so take it off slightly before your target temperature. Let meat rest for a few minutes before cutting."),
            (.user, "My pasta always turns out mushy. What's the secret to perfect pasta?"),
            (.assistant, "The key is using plenty of well-salted water (it should taste like the sea), boiling it vigorously before adding pasta, and not overcooking it. Check the package directions but start testing a minute or two before the suggested time. The pasta should be \"al dente\" - firm to the bite with a slight resistance. Save some pasta water before draining - the starchy water is great for helping sauce stick to the pasta!"),
            (.user, "What's the best way to store fresh herbs?"),
            (.assistant, "For tender herbs like basil, cilantro, and parsley, trim the stems and place them in a jar with water (like a bouquet), then cover loosely with a plastic bag and refrigerate. For hardier herbs like rosemary and thyme, wrap them in a slightly damp paper towel and store in a plastic bag in the fridge. You can also freeze herbs in oil or water in ice cube trays for longer storage."),
            (.user, "I want to learn how to make bread. Is it difficult?"),
            (.assistant, "Bread making can seem intimidating, but it's actually quite achievable! Start with a simple no-knead bread recipe - it's almost foolproof and will build your confidence. The key ingredients are just flour, water, salt, and yeast. Time and temperature are crucial - be patient with rising times. As you get comfortable, you can try more complex recipes. Start simple and don't be discouraged if your first loaf isn't perfect!"),
            (.user, "How do I make my vegetables taste better?"),
            (.assistant, "The secret to great vegetables is proper seasoning and cooking technique. Don't be shy with salt - it brings out the natural flavors. Try roasting vegetables with olive oil, salt, and pepper - it caramelizes them and creates amazing flavor. Don't overcook them - most vegetables are best when they still have some bite. Try different cooking methods: steaming, roasting, sautéing, or grilling can all bring out different flavors in the same vegetable."),
            (.user, "What's the difference between baking soda and baking powder?"),
            (.assistant, "Baking soda needs an acid (like vinegar, lemon juice, or buttermilk) to activate and create bubbles that make things rise. Baking powder contains both an acid and a base, so it activates when mixed with liquid. Most recipes specify which to use. Baking soda is more powerful, so you use less of it. Make sure they're fresh - they lose their effectiveness over time. You can test baking powder by mixing it with water - it should bubble immediately."),
            (.user, "How can I make my cooking more flavorful without adding too much salt?"),
            (.assistant, "Great question! There are many ways to add flavor. Use aromatics like garlic, onions, and herbs. Add a splash of acid (lemon juice, vinegar) at the end to brighten flavors. Use spices and spice blends. Add umami-rich ingredients like mushrooms, tomatoes, or soy sauce. Toast spices before using them to enhance their flavor. Use quality ingredients - fresh herbs and spices make a huge difference. Caramelize onions to add sweetness and depth. These techniques create complex flavors beyond just saltiness."),
            (.user, "What's the best way to cook rice? Mine always turns out sticky or mushy."),
            (.assistant, "Perfect rice requires the right ratio and technique! For most white rice, use 1.5 cups water to 1 cup rice. Rinse the rice until water runs clear to remove excess starch. Use a heavy-bottomed pot with a tight-fitting lid. Bring rice and water to a boil, then immediately reduce to lowest heat and cover. Don't peek! Cook for 18-20 minutes, then remove from heat and let steam for 10 minutes with lid on. Fluff with a fork. For brown rice, use 2 cups water to 1 cup rice and cook 45-50 minutes. A rice cooker makes this foolproof, but the stovetop method works great too. The key is not lifting the lid during cooking and letting it steam afterward."),
            (.user, "How do I properly sear meat to get that restaurant-quality crust?"),
            (.assistant, "A perfect sear requires high heat, dry meat, and patience! Start by patting the meat completely dry with paper towels - moisture is the enemy of browning. Season generously with salt and pepper. Heat your pan (cast iron or stainless steel work best) over high heat until it's very hot - you should see a slight shimmer. Add a high-smoke-point oil (avocado, grapeseed, or vegetable oil). When oil shimmers, add the meat. Don't move it! Let it sear for 2-4 minutes until a golden-brown crust forms. Flip only once. Don't overcrowd the pan - cook in batches if needed. The meat should release easily when ready. For steaks, let them rest at room temperature 30 minutes before cooking. The Maillard reaction (browning) happens at high heat with dry surfaces - that's what creates that amazing flavor and crust!"),
            (.user, "What's the difference between sautéing, pan-frying, and stir-frying?"),
            (.assistant, "These techniques differ in heat, oil amount, and movement! Sautéing uses medium-high heat with a small amount of fat, and you toss or flip ingredients frequently. It's great for vegetables and quick-cooking items. Pan-frying uses more oil (enough to come partway up the food) at medium heat, and you flip items once. Think fried chicken or fish fillets. Stir-frying uses very high heat, a small amount of oil, and constant stirring/tossing. It's the fastest method, perfect for Asian dishes. The key differences: sauté = medium heat, little oil, frequent movement. Pan-fry = medium heat, more oil, flip once. Stir-fry = very high heat, little oil, constant movement. Each technique creates different textures and flavors!"),
            (.user, "How do I know when fish is cooked? I'm always worried about undercooking it."),
            (.assistant, "Fish is done when it's opaque and flakes easily! For most fish fillets, cook until the flesh turns from translucent to opaque white. The general rule is 10 minutes per inch of thickness at 400°F. You can test by inserting a fork - if it flakes easily and the center is opaque, it's done. For salmon, aim for 125-130°F internal temperature (medium-rare) or 140°F (well-done). Undercooked fish is still translucent and won't flake. Overcooked fish is dry and tough. A meat thermometer helps - most fish is done at 145°F, but salmon and tuna can be enjoyed at lower temps. The \"10-minute rule\" is a good starting point: 10 minutes per inch, measured at the thickest part. When in doubt, slightly undercook - you can always cook more, but you can't undo overcooking!"),
            (.user, "What's the secret to making perfect scrambled eggs?"),
            (.assistant, "Perfect scrambled eggs are all about low heat and patience! Crack eggs into a bowl, add a splash of milk or cream (optional), and whisk until just combined - don't overbeat. Heat butter in a non-stick pan over LOW heat. Add eggs and let them set slightly before gently pushing from edges to center with a spatula. Continue this gentle motion, creating soft curds. Remove from heat just before they look done - they'll finish cooking from residual heat. Season with salt and pepper at the end (salt too early can make them watery). For creamy eggs, stir constantly. For larger curds, let them set more between stirs. The key is low, slow heat - high heat makes rubbery eggs. French-style scrambled eggs are even creamier - cook over very low heat, stirring constantly with a spatula until they're just set but still creamy."),
            (.user, "How do I make a good homemade pasta sauce from scratch?"),
            (.assistant, "A great pasta sauce starts with quality ingredients and proper technique! For a simple marinara: heat olive oil, add finely chopped garlic (don't let it brown), add a can of good quality crushed tomatoes, season with salt, pepper, and a pinch of sugar to balance acidity. Simmer 20-30 minutes until thickened. For a richer sauce, start by sautéing onions until soft, then add garlic. Add tomatoes, a bay leaf, and let it simmer longer (45-60 minutes). Finish with fresh basil. For meat sauce, brown ground meat first, then add aromatics and tomatoes. The key is using good canned tomatoes (San Marzano are excellent), cooking long enough to develop flavor, and seasoning properly. Don't skip the sugar - it really helps balance the tomato acidity. Fresh herbs should go in at the end. Taste and adjust seasoning as it cooks!"),
            (.user, "What's the best way to store leftovers to keep them fresh?"),
            (.assistant, "Proper storage prevents food waste and keeps food safe! Cool food quickly - don't put hot food directly in the fridge (it raises fridge temp). Divide large portions into smaller containers for faster cooling. Use airtight containers - glass is best as it doesn't absorb odors. Label containers with dates. Most cooked foods last 3-4 days in the fridge. Freeze what you won't eat in that time. Reheat leftovers to 165°F to kill bacteria. For soups and stews, they often taste better the next day as flavors meld. Rice should be cooled quickly and refrigerated within 1 hour - it can grow bacteria if left out. Pasta can be stored with a bit of oil to prevent sticking. Bread freezes well - slice before freezing for easy use. When in doubt, follow the \"when in doubt, throw it out\" rule for safety!"),
            (.user, "How do I make my own chicken stock? Is it worth the effort?"),
            (.assistant, "Homemade stock is absolutely worth it - the flavor difference is incredible! Start with chicken bones (save them from roasted chicken or buy chicken backs/necks). Roast bones in the oven first for deeper flavor (optional but recommended). Put bones in a large pot, cover with cold water, add aromatics: onion (quartered), carrots, celery, garlic, bay leaves, peppercorns, and fresh herbs like thyme or parsley. Bring to a boil, then reduce to a gentle simmer. Skim off any foam that rises. Simmer for 3-4 hours (longer for more flavor). Strain through a fine-mesh sieve, discard solids. Let cool, then refrigerate - fat will rise to top and solidify (remove it). Freeze in portions. The key is low, slow simmering - don't let it boil hard. Homemade stock has much more flavor and body than store-bought, and you control the salt. It's perfect for soups, risottos, and sauces. Freeze in ice cube trays for easy portioning!"),
            (.user, "What's the difference between braising, stewing, and roasting?"),
            (.assistant, "These cooking methods differ in liquid amount and temperature! Braising involves browning meat first, then cooking it partially submerged in liquid (wine, stock, or sauce) at low temperature in a covered pot. It's great for tougher cuts like pot roast or short ribs. The liquid creates steam and tenderizes the meat. Stewing is similar but the meat is completely covered in liquid and cut into smaller pieces. Think beef stew or chicken fricassee. Roasting uses dry heat in an oven - no liquid, just hot air circulating around the food. It's for larger cuts of meat or whole birds. The key differences: braise = partial liquid, covered, low heat, large pieces. Stew = full liquid, covered, low heat, small pieces. Roast = no liquid, uncovered, higher heat, large pieces. Each method creates different textures and flavors - braising and stewing make meat tender and create rich sauces, while roasting creates crispy exteriors and concentrates flavors."),
            (.user, "How do I prevent vegetables from getting soggy when cooking?"),
            (.assistant, "Soggy vegetables are usually caused by overcooking or too much moisture! For steaming, don't overcook - vegetables should be crisp-tender, not mushy. Remove from heat and immediately run under cold water to stop cooking. For roasting, don't overcrowd the pan - vegetables need space for moisture to evaporate. Use high heat (400-425°F) to caramelize and crisp. Toss with just enough oil to coat, not drench. For sautéing, use high heat and don't cover the pan (traps steam). Don't add salt too early - it draws out moisture. For stir-frying, have everything prepped and cook quickly over very high heat. The key is high heat, quick cooking, and proper spacing. Undercook slightly - vegetables continue cooking after removal from heat. For salads, dry vegetables thoroughly after washing. Remember: crisp-tender is the goal, not soft and mushy!"),
            (.user, "What's the best way to learn knife skills? I'm always cutting myself."),
            (.assistant, "Knife skills are fundamental and improve with practice! Start with a sharp knife - dull knives are actually more dangerous because they slip. Learn the proper grip: pinch the blade between your thumb and forefinger, wrap other fingers around the handle. Use a claw grip with your non-knife hand - curl your fingers under so your knuckles guide the knife. Keep the tip of the knife on the cutting board and use a rocking motion. Practice basic cuts: julienne (matchsticks), dice (small cubes), chiffonade (thin ribbons for herbs). Start slow and focus on technique, not speed. Always cut away from your body. Keep your cutting board stable (put a damp towel underneath). Practice with softer vegetables first like onions and carrots before moving to harder items. Watch tutorial videos to see proper technique. The key is consistent practice - even 10 minutes a day helps. Remember: speed comes after accuracy. Safety first!"),
            (.user, "How do I make restaurant-quality sauces at home?"),
            (.assistant, "Restaurant sauces often use techniques you can master at home! Start with a good foundation - many sauces begin with aromatics (onions, garlic) cooked slowly until soft and sweet. Learn to make a roux (equal parts fat and flour) for creamy sauces - cook it until it's the right color (blond for white sauces, darker for brown sauces). Deglazing the pan after cooking meat creates incredible flavor - add wine, stock, or even water and scrape up the browned bits. Reduce liquids to concentrate flavors - simmer until sauce coats the back of a spoon. Finish with butter (mounting) for richness and shine. Season properly - taste and adjust salt, acid, and sweetness. Fresh herbs should go in at the end. Many restaurant sauces use stock as a base - homemade stock makes a huge difference. Don't be afraid of fat - it carries flavor. Practice the five mother sauces: béchamel, velouté, espagnole, hollandaise, and tomato. Master these and you can make countless variations!"),
            (.user, "What's the difference between all the different types of salt? Does it matter?"),
            (.assistant, "Salt types do matter, but not as much as some claim! Table salt is fine-grained and has additives (anti-caking agents) and sometimes iodine. It's very salty and dissolves quickly. Kosher salt has larger flakes, no additives, and is less dense - you need more by volume for the same saltiness. It's great for general cooking. Sea salt varies by source and can have trace minerals that add subtle flavors. It's often used as finishing salt. Himalayan pink salt is mostly marketing - it's just rock salt with trace minerals. Flaky sea salt (like Maldon) is expensive but perfect for finishing - it adds texture and bursts of saltiness. For everyday cooking, kosher salt is ideal - it's easy to control, dissolves well, and has no additives. For finishing, flaky sea salt adds elegance. The key is using the right salt for the right purpose. Don't overthink it - consistent use of one type helps you learn to season properly. The most important thing is tasting as you cook!"),
            (.user, "How do I properly store different types of food to maximize freshness?"),
            (.assistant, "Proper storage extends food life and maintains quality! For vegetables: most should be stored in the fridge, but some exceptions: potatoes and onions in a cool, dark place (not together - onions make potatoes sprout), tomatoes at room temperature until ripe, then fridge, and bananas separate from other fruits. Leafy greens should be washed, dried thoroughly, and stored in containers with paper towels. Herbs: tender ones in water like flowers, hardier ones wrapped in damp paper towels. For meat: store in the coldest part of the fridge (usually bottom shelf), use within 1-2 days or freeze. Freeze in portions you'll use. For dairy: keep milk and cream in the main fridge (not door - too warm), butter can stay out if you use it quickly. Bread: room temperature for short term, freeze for longer. Store in airtight containers to prevent staleness. Label and date everything. The key is understanding each food's needs - some need airflow, some need to be sealed, some need moisture, some need to be dry. When in doubt, follow the 'first in, first out' rule to prevent waste."),
        ]
        return MockConversationPreset(
            name: "Cooking Tips",
            description: "Cooking advice and recipe discussions (20+ messages)",
            messages: messages,
            transcript: createTranscript(from: messages)
        )
    }()
    
    static let bookDiscussion: MockConversationPreset = {
        let messages: [(role: MessageRole, content: String)] = [
            (.user, "I'm looking for a good book to read. What would you recommend?"),
            (.assistant, "That depends on what you enjoy! Are you interested in fiction or non-fiction? For fiction, I'd recommend classics like \"To Kill a Mockingbird\" by Harper Lee or \"1984\" by George Orwell if you like thought-provoking stories. For contemporary fiction, \"The Seven Husbands of Evelyn Hugo\" by Taylor Jenkins Reid is engaging. If you prefer non-fiction, \"Sapiens\" by Yuval Noah Harari is fascinating. What genres do you typically enjoy?"),
            (.user, "I love mystery novels. What are some must-reads in that genre?"),
            (.assistant, "For mystery lovers, you can't go wrong with Agatha Christie - start with \"Murder on the Orient Express\" or \"And Then There Were None.\" Modern mystery masters include Tana French's Dublin Murder Squad series, starting with \"In the Woods.\" \"Gone Girl\" by Gillian Flynn is a fantastic psychological thriller. For classic detective stories, try Sherlock Holmes by Arthur Conan Doyle or Raymond Chandler's Philip Marlowe novels."),
            (.user, "I've been meaning to read more classics. Where should I start?"),
            (.assistant, "Great choice! Classics can be intimidating, but start with shorter, more accessible ones. \"The Great Gatsby\" by F. Scott Fitzgerald is beautiful and relatively short. \"Of Mice and Men\" by John Steinbeck is powerful and quick to read. \"Pride and Prejudice\" by Jane Austen is witty and charming. \"Animal Farm\" by George Orwell is short but impactful. Once you're comfortable, move on to longer classics like \"Jane Eyre\" or \"Les Misérables.\" What themes interest you?"),
            (.user, "What about science fiction? I've never really tried that genre."),
            (.assistant, "Science fiction is wonderful and very diverse! Start with accessible classics like \"Dune\" by Frank Herbert for epic space opera, or \"The Martian\" by Andy Weir for a more grounded, humorous take. \"Project Hail Mary\" by the same author is fantastic. For thought-provoking stories, try \"The Left Hand of Darkness\" by Ursula K. Le Guin. \"Ender's Game\" by Orson Scott Card is great for newcomers. If you like dystopian themes, \"The Handmaid's Tale\" by Margaret Atwood blends sci-fi with social commentary."),
            (.user, "I don't have much time to read. Any tips for fitting reading into a busy schedule?"),
            (.assistant, "Absolutely! Try audiobooks during commutes or while doing chores - they're a great way to 'read' when you can't sit down. Carry a book or e-reader with you to read during waiting times. Set a small daily goal - even 10-15 minutes adds up. Read before bed instead of scrolling on your phone. Join or start a book club for accountability and social reading. Short stories and novellas are perfect for busy schedules. Remember, any reading is better than none!"),
            (.user, "What's the best way to remember what I've read?"),
            (.assistant, "Good question! Try taking notes as you read - jot down key points, favorite quotes, or your thoughts. Underline or highlight passages that resonate with you. Write a brief summary after finishing each book. Discuss books with others - talking about what you've read helps retention. Join a book club for deeper discussion. Keep a reading journal to track themes and connections between books. Re-reading favorite passages can also help. The act of engaging actively with the text is what helps you remember."),
            (.user, "Should I read physical books or e-books? What's better?"),
            (.assistant, "There's no right answer - it depends on personal preference! Physical books offer tactile satisfaction and you can easily flip back to previous pages. E-books are convenient, portable, and great for traveling or reading in bed without a light. Many people find they read faster on e-readers. Some prefer the smell and feel of paper. I'd say try both and see what works for you. Many people use a combination - e-books for convenience, physical books for favorites they want to keep."),
            (.user, "I want to read more non-fiction. What topics are most interesting?"),
            (.assistant, "Non-fiction is incredibly diverse! Popular topics include history (try \"Sapiens\" or \"Guns, Germs, and Steel\"), science (\"A Brief History of Time\" or \"The Immortal Life of Henrietta Lacks\"), biographies (\"The Autobiography of Malcolm X\" or \"Steve Jobs\"), psychology (\"Thinking, Fast and Slow\" or \"The Power of Habit\"), and memoirs (\"Educated\" or \"When Breath Becomes Air\"). Pick topics you're curious about - that curiosity will keep you engaged. What interests you most?"),
            (.user, "How do I choose which book to read next when there are so many options?"),
            (.assistant, "It can be overwhelming! Start by considering your mood - what do you feel like reading right now? Keep a \"to-read\" list of books that catch your interest. Ask friends for recommendations. Check out book reviews or bestseller lists. Try the \"first page test\" - read the first page and see if it draws you in. Don't feel obligated to finish every book - life's too short for books you're not enjoying. Sometimes the best book is the one that speaks to you in this moment."),
            (.user, "What are some great fantasy series I should check out?"),
            (.assistant, "Fantasy offers incredible worlds to explore! For epic fantasy, \"The Lord of the Rings\" by J.R.R. Tolkien is the foundation of the genre. \"A Song of Ice and Fire\" by George R.R. Martin (Game of Thrones) is complex and political. \"The Stormlight Archive\" by Brandon Sanderson has amazing world-building. For urban fantasy, try \"The Dresden Files\" by Jim Butcher or \"American Gods\" by Neil Gaiman. \"The Name of the Wind\" by Patrick Rothfuss has beautiful prose. \"Mistborn\" by Sanderson is great for newcomers. \"The Wheel of Time\" by Robert Jordan is epic (14 books!). \"The Broken Earth\" trilogy by N.K. Jemisin is award-winning and unique. \"The Poppy War\" by R.F. Kuang blends fantasy with Chinese history. Start with shorter series if you're new to fantasy, then dive into the epics!"),
            (.user, "I want to read more diverse authors. Can you recommend some?"),
            (.assistant, "Absolutely! Reading diverse voices enriches your perspective. For contemporary fiction: \"The Seven Husbands of Evelyn Hugo\" and \"Malibu Rising\" by Taylor Jenkins Reid, \"The Vanishing Half\" by Brit Bennett, \"Such a Fun Age\" by Kiley Reid. For literary fiction: \"The Color Purple\" by Alice Walker, \"Beloved\" by Toni Morrison, \"The Joy Luck Club\" by Amy Tan. For sci-fi/fantasy: \"The Broken Earth\" trilogy by N.K. Jemisin, \"Binti\" by Nnedi Okorafor, \"The Poppy War\" by R.F. Kuang. For memoirs: \"Educated\" by Tara Westover, \"Born a Crime\" by Trevor Noah, \"I Know Why the Caged Bird Sings\" by Maya Angelou. For international authors: \"Pachinko\" by Min Jin Lee, \"The Kite Runner\" by Khaled Hosseini, \"One Hundred Years of Solitude\" by Gabriel García Márquez. These authors bring unique perspectives and incredible storytelling!"),
            (.user, "What makes a book a 'classic'? How do books become classics?"),
            (.assistant, "Classics typically have several qualities: they stand the test of time (remain relevant decades or centuries later), have universal themes that resonate across cultures and eras, demonstrate literary excellence in writing style and technique, offer deep insights into human nature or society, and influence other writers and literature. Books become classics through a combination of critical acclaim, academic study, cultural impact, and continued readership. Some become classics immediately (like \"To Kill a Mockingbird\"), while others gain status over time. Classics often reflect their historical period while speaking to timeless human experiences. They're frequently taught in schools, referenced in other works, and adapted into films. However, the canon is evolving - books by women, people of color, and authors from diverse backgrounds are being recognized as classics that were previously overlooked. A classic isn't just old - it's a book that continues to speak to readers generation after generation."),
            (.user, "How do I get back into reading after not reading for a long time?"),
            (.assistant, "Getting back into reading is all about starting small and finding what you enjoy! Begin with shorter books or novellas - don't tackle \"War and Peace\" right away. Try genres you enjoyed before, or explore something completely new. Set a small daily goal - even 10-15 minutes. Read before bed instead of scrolling on your phone. Join a book club for accountability and social motivation. Try audiobooks - they're great for commutes or chores. Re-read an old favorite to remind yourself why you love reading. Visit a bookstore or library and browse - sometimes the right book finds you. Don't force yourself to finish books you're not enjoying - life's too short. Start with page-turners or fast-paced books to build momentum. Remember, any reading is good reading - graphic novels, short stories, magazines all count. The key is making it a habit again, not reading the \"right\" books."),
            (.user, "What's the difference between literary fiction and genre fiction?"),
            (.assistant, "The main difference is focus and purpose! Literary fiction emphasizes character development, prose style, and exploring themes about human nature, society, or life. It's often character-driven rather than plot-driven. Genre fiction (mystery, sci-fi, romance, fantasy, thriller) emphasizes plot, entertainment, and following conventions of that genre. Literary fiction might be slower-paced and more introspective, while genre fiction is usually faster-paced and plot-focused. However, these categories often overlap - many books blend literary quality with genre elements. \"The Handmaid's Tale\" is literary fiction with sci-fi elements. \"The Name of the Wind\" is fantasy with literary prose. \"Gone Girl\" is a thriller with literary depth. The distinction can be arbitrary - great writing exists in both categories. Don't let labels limit what you read. Many genre books have literary merit, and literary fiction can be thrilling. Read what you enjoy, regardless of category!"),
            (.user, "I want to understand poetry better. Where should I start?"),
            (.assistant, "Poetry can seem intimidating, but it's accessible once you find your way in! Start with contemporary poets - they use modern language and relatable themes. Try Mary Oliver for nature and life reflections, Rupi Kaur for accessible modern verse, or Billy Collins for humor and everyday moments. Read poetry anthologies to sample different styles. Don't worry about \"getting\" every poem - poetry is meant to be felt and experienced, not decoded. Read poems aloud - the sound and rhythm are part of the experience. Start with shorter poems before tackling epics. Poetry collections by a single author let you get familiar with their voice. \"A Poetry Handbook\" by Mary Oliver explains techniques without being academic. Join a poetry reading group or attend open mic nights. Remember, there's no \"right\" way to interpret poetry - your response is valid. Poetry is about emotion, imagery, and language - let it wash over you rather than analyzing every line."),
            (.user, "What are some must-read books about history?"),
            (.assistant, "Great history books read like stories! \"Sapiens\" by Yuval Noah Harari covers human history in an engaging way. \"Guns, Germs, and Steel\" by Jared Diamond explores why civilizations developed differently. \"A People's History of the United States\" by Howard Zinn offers perspectives often left out of textbooks. \"The Rise and Fall of the Third Reich\" by William Shirer is a comprehensive WWII account. \"1491\" by Charles Mann reveals pre-Columbian Americas. \"The Warmth of Other Suns\" by Isabel Wilkerson tells the Great Migration story. \"The Silk Roads\" by Peter Frankopan reframes world history through trade routes. \"SPQR\" by Mary Beard makes ancient Rome accessible. \"The Swerve\" by Stephen Greenblatt shows how one book changed the world. \"The Immortal Life of Henrietta Lacks\" blends science and social history. Look for narrative history - books that tell history as a story rather than dry facts. The best history books make the past come alive and feel relevant to today."),
            (.user, "How do book adaptations compare to the original books?"),
            (.assistant, "Adaptations are interpretations, not replacements! Books can include internal thoughts, detailed descriptions, and subplots that films can't easily show. Films must condense and visualize, which means some things get cut or changed. Some adaptations are very faithful (\"The Lord of the Rings\"), while others take creative liberties (\"The Shining\"). Generally, the book has more depth and detail, while the film offers visual storytelling and pacing. Some stories work better in their adapted form - \"The Godfather\" film is often considered better than the book. Others lose something in translation - \"The Time Traveler's Wife\" book has more emotional depth. My advice: read the book first if you want the full experience, then watch the adaptation to see how it was interpreted. Or watch first, then read to get the deeper story. Both can be enjoyed on their own terms. The key is understanding they're different art forms with different strengths. Don't expect a film to include everything from a 500-page book - that's not how adaptation works!"),
            (.user, "What are some great short story collections I should read?"),
            (.assistant, "Short stories are perfect for busy schedules and offer complete narratives in compact form! \"The Things They Carried\" by Tim O'Brien (Vietnam War stories that blur fiction and memoir). \"Interpreter of Maladies\" by Jhumpa Lahiri (beautiful stories about Indian immigrants). \"The Complete Stories\" by Flannery O'Connor (Southern Gothic at its finest). \"Dubliners\" by James Joyce (masterful portraits of early 20th century Ireland). \"The Lottery and Other Stories\" by Shirley Jackson (unsettling and brilliant). \"What We Talk About When We Talk About Love\" by Raymond Carver (minimalist perfection). \"Her Body and Other Parties\" by Carmen Maria Machado (genre-bending feminist stories). \"The Paper Menagerie\" by Ken Liu (sci-fi and fantasy short stories). \"Tenth of December\" by George Saunders (contemporary and thought-provoking). \"The Best American Short Stories\" annual collections offer great variety. Short stories are perfect for discovering new authors, trying different genres, and fitting reading into busy days. Each story is a complete world in miniature!"),
            (.user, "How do I build a better reading habit? I want to read more but struggle to find time."),
            (.assistant, "Building a reading habit is about making it easy and enjoyable! Start small - even 10-15 minutes a day adds up to several books a year. Set a specific time: first thing in the morning, during lunch, or before bed. Replace phone scrolling with reading - keep a book on your nightstand instead of your phone. Always carry a book or e-reader for waiting times (doctor's office, commute, coffee shop). Set realistic goals - don't aim for 100 books if you're not reading now. Try 12 books a year (one per month) or even one book every two months. Join a book club for accountability and social motivation. Track your reading (Goodreads, journal, or simple list) - seeing progress is motivating. Read what you enjoy, not what you think you should read. Mix formats - physical books, e-books, audiobooks all count. Don't force yourself to finish books you're not enjoying - life's too short. The key is consistency over quantity. Make reading a ritual, not a chore. Even 20 pages a day is 7,300 pages a year - that's a lot of books!"),
            (.user, "What's the best way to take notes while reading? I want to remember more."),
            (.assistant, "Note-taking while reading deepens understanding and helps retention! Methods vary by purpose: For fiction: mark beautiful passages, note character development, track themes, and jot down questions or predictions. For non-fiction: summarize key points in your own words, note important facts or statistics, write down questions that arise, and connect ideas to what you already know. Physical books: use sticky notes, underline sparingly (only truly important parts), write in margins (your thoughts, questions, connections). E-books: use highlighting and note features, export notes periodically. Keep a reading journal: write a brief summary after each chapter or reading session, note favorite quotes, reflect on what you learned or how it changed your thinking. Create a system: some people use index cards, others use apps like Notion or Obsidian. The key is active engagement - writing helps you process and remember. Don't overdo it - too many notes can interrupt flow. Find a balance between reading and reflecting. Review your notes periodically to reinforce learning. The act of writing itself helps memory, so even brief notes are valuable."),
            (.user, "Should I read multiple books at once or focus on one at a time?"),
            (.assistant, "Both approaches work - it depends on your personality and goals! Reading one book at a time keeps you focused and helps you fully immerse in the story or topic. You're less likely to confuse plots or forget details. It's simpler and requires less mental juggling. However, reading multiple books can work well if you choose different types: maybe one fiction and one non-fiction, or one heavy book and one lighter one. Some people read different books for different contexts - a serious book at home, a lighter one for commutes. The key is not having too many going at once - 2-3 is usually manageable, more than that and you risk not finishing any. Consider your reading speed and available time. If you're a slow reader or have limited time, one at a time might be better. If you get bored easily or like variety, multiple books can keep you engaged. The most important thing is actually finishing books - if reading multiple means you abandon them all, stick to one. Experiment and see what works for you. There's no right answer - the best reading method is the one that keeps you reading!"),
            (.user, "How do I choose my next book when there are so many options? I get overwhelmed."),
            (.assistant, "Book choice overwhelm is real! Here are strategies: Start with your mood - what do you feel like reading right now? Light and fun? Deep and thought-provoking? Fast-paced thriller? Keep a 'to-read' list (Goodreads, notes app, or physical list) - when you hear about a book, add it immediately so you don't forget. Ask friends for recommendations - people who know you often suggest perfect books. Try the 'first page test' - read the first page in a bookstore or library. If it doesn't grab you, move on. Check out 'best of' lists for your favorite genres. Read reviews, but don't let them decide for you - everyone's taste differs. Re-read an old favorite if you're stuck - sometimes you need something familiar. Try a book by an author you've enjoyed before. Don't overthink it - sometimes you just need to pick something and start. Remember, you can always stop if it's not working. The perfect book is the one you want to read right now, not the one you think you should read. Trust your instincts and don't let the abundance of choices paralyze you - any reading is good reading!"),
        ]
        return MockConversationPreset(
            name: "Book Discussion",
            description: "Talking about books and reading recommendations (20+ messages)",
            messages: messages,
            transcript: createTranscript(from: messages)
        )
    }()
    
    private static func createTranscript(from messages: [(role: MessageRole, content: String)]) -> Transcript {
        var entries: [Transcript.Entry] = []
        
        for (role, content) in messages {
            switch role {
            case .user:
                let prompt = Transcript.Prompt(
                    segments: [.text(Transcript.TextSegment(content: content))]
                )
                entries.append(.prompt(prompt))
            case .assistant:
                let response = Transcript.Response(
                    assetIDs: [],
                    segments: [.text(Transcript.TextSegment(content: content))]
                )
                entries.append(.response(response))
            case .system:
                break
            }
        }
        
        return Transcript(entries: entries)
    }
}
